import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono } from "next/font/google";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

import { DirectionProvider } from "@/components/ui/direction"
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getLocale } from "next-intl/server";
import { getDirection } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n";

const fontSans = localFont({
  src: [
    { path: "../public/fonts/Swis721-Light.woff2", weight: "300" },
    { path: "../public/fonts/Swis721-Regular.woff2", weight: "400" },
    { path: "../public/fonts/Swis721-Bold.woff2", weight: "700" },
  ],
  variable: "--font-sans",
});
const fontSerif = localFont({
  src: [
    { path: "../public/fonts/Bahij-SemiLight.woff2", weight: "300" },
    { path: "../public/fonts/Bahij-Bold.woff2", weight: "700" },
  ],
  variable: "--font-serif",
});
const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale() as Locale;
  const messages = await getMessages();

  return (
    <html lang={locale} dir={getDirection(locale)} suppressHydrationWarning>
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider messages={messages}>
            <DirectionProvider dir={getDirection(locale)}>
              {children}
            </DirectionProvider>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
